### ISSUE TITLE
CEC no longer working to turn off TV

### ISSUE THREAD

**Issue by satmandu** [add-ons/screensaver.turnoff#17]
I'm using kodi on ubuntu 20.04 (now updated to groovy) using the kodi-stable ppa.

I get this message in the kodi log when I try to manually preview.
```NOTICE: [screensaver.turnoff] Executing builtin 'CECStandby'```

This used to work perfectly fine before.  I've tried updating libcec to 5.0 but that didn't help. 

Running ```echo 'standby 0.0.0.0' | cec-client -s -d 1``` with kodi quit works just fine.

Any ideas on what to try next?

**Comment by dagwieers** [comment]
If the CECStandby built-in stopped working for you, that would be a regression in Kodi.
You can run: `kodi-send -a CECStandby` on your Kodi system to trigger this yourself.

I would check upstream forums/issues and eventually report this upstream.

**Comment by satmandu** [comment]
It does appear to be broken on my system with Matrix. I'll report it upstream.

**Comment by dagwieers** [comment]
Aha, this is related to Matrix? I assumed it was Leia because of the name `kodi-stable` :-)
You may have the same problem as reported in #18

**Comment by satmandu** [comment]
(Tried with Leia - didn't work, and then was told that there were no updates to Leia, so now trying with Matrix.)

I am the reporter for https://github.com/add-ons/screensaver.turnoff/issues/18 ;)

**Comment by satmandu** [comment]
Turns out I am hitting a bug in the CEC config interface.  I need to set the "Devices to Power off during shutdown" to include "TV" to make CECStandby work.
