### ISSUE TITLE
Not available in 19.x?

### ISSUE THREAD

**Issue by satmandu** [add-ons/screensaver.turnoff#18]
As per https://github.com/xbmc/xbmc/issues/18225#issuecomment-665264070 all development has moved to 19.x, so it would be nice to have this available. I'm currently trying to make sure that cec works in 19.x as per https://github.com/xbmc/xbmc/issues/18224

**Comment by dagwieers** [comment]
If you want to test this add-on on Matrix, the change to addon.xml that is needed is trivial.

**Comment by satmandu** [comment]
Thanks. I realized this and made the change. Still trying to debug the other error in Matrix...
