### ISSUE TITLE
Method to turn off official RPi 7 inch touch screen

### ISSUE THREAD

**Issue by ejvanstein** [add-ons/screensaver.turnoff#3]
Can you please add another method that turns off the backlight of the official RPi 7 inch touch screen? The command to turn it off is:
```
run_command(['su -c "echo 1 >/sys/class/backlight/rpi_backlight/bl_power"'], shell=True)
```
The command to turn it back on is:
```
run_command(['su -c "echo 0 >/sys/class/backlight/rpi_backlight/bl_power"'], shell=True)
```
Confirmed to work on RPi 3b with LibreELEC.

**Comment by dagwieers** [comment]
It seems more logical the 0 means off, and 1 means on, but other documentation seems to indicate this was not a typo ;-)

**Comment by dagwieers** [comment]
Thanks for reporting !

**Comment by dagwieers** [comment]
Also please test and report back.
